### ISSUE TITLE
Update to newer version Poppler

### ISSUE THREAD

**Issue by Rockstar04** [pdf2htmlEX/pdf2htmlEX#10] opened 2018-01-23 17:53 UTC
There is an outstanding [pull request](https://github.com/coolwanglu/pdf2htmlEX/pull/738) in the parent repository to allow a newer version of Poppler  as well as the [initial issue](https://github.com/coolwanglu/pdf2htmlEX/issues/733)  reporting the incompatibility

**Comment by amit777** [comment] 2019-02-22 08:58
so after much hacking around, 

I think I got your branch working with Poppler .74 + Cairo 1.6
```
bash-4.4# pdf2htmlEX --version
pdf2htmlEX version 0.15.0
Copyright 2012-2015 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.74.0
  libfontforge 20190222
  cairo 1.16.0
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg svg
```

I'm trying to track down a subtle issue with a transformation matrix.. 


In the older version of pdf2htmlEX run from Mac brew install we get this (which works):

```
.m0{transform:none;-ms-transform:none;-webkit-transform:none;}
```

In the newer version from your branch we get the following transform:
```
.m0{transform:matrix(0.000000,0.000000,0.000000,0.000000,0,0);-ms-transform:matrix(0.000000,0.000000,0.000000,0.000000,0,0);-webkit-transform:matrix(0.000000,0.000000,0.000000,0.000
000,0,0);}
```

It's something in the code from src/StateManager.h

class TransformMatrixManager : public StateManager<Matrix, TransformMatrixManager>
...

This is where my knowledge ends.. Any idea why the newer version of the code would generate a different matrix like that?  It's causing a div to be invisible and a surrounding link to not be clickable because of it.

I can privately share a copy of the PDF that causing the issue if it's helpful.

**Comment by amit777** [comment] 2019-02-22 08:59
Also, when I got my version working, I cloned from Rockstar04/pdf2htmlEX rather than pdf2htmlEX/pdf2htmlEX.  Did I use the correct one?

**Comment by amit777** [comment] 2019-02-22 10:19
so after much more digging, this transform issue I'm seeing may be due to this bug that was recenlty filed:
https://gitlab.freedesktop.org/poppler/poppler/issues/721  will keep an eye out for a fix.

**Comment by Rockstar04** [comment] 2019-02-22 14:13
Thanks for the work you've done here @amit777 !

I'm not sure if you can open a pull request with your changes, but it would help greatly to review what you have changed, and anything else that may need done before merging.

**Comment by amit777** [comment] 2019-02-22 15:48
@Rockstar04 thank you, but just wanted to clarify, do you think i should be using the pdf2htmlEX/pdf2htmlEX branch or the Rockstar04/pdf2htmlEX branch?    Or should I just start from coolwanglu's branch?

**Comment by Rockstar04** [comment] 2019-02-22 15:52
Hopefully pdf2htmlEX/pdf2htmlEX and Rockstar04/pdf2htmlEX are not very different, but I will definitely suggest you branch from the "official" pdf2htmlEX/pdf2htmlEX repo.

coolwanglu's repository has been archived and should not be used.

**Comment by amit777** [comment] 2019-02-22 18:46
gotcha.. Also, I noticed a knowledgable contributor in the forums named David Hedley who has a bunch of fixes in his branch https://github.com/davidhedley/pdf2htmlEX

I'm going to spend a little time to see if they should be merged.  The problem is I have very little clue on how the internals of all this stuff is supposed to work!

**Comment by Rockstar04** [comment] 2019-02-22 19:31
I dont know much about the internal working at this point either, and I know very little about C++.

**Comment by amit777** [comment] 2019-02-22 19:40
so it's strange.. I'm doing a manual diff between davidhedleys fork and this fork and most of his changes are incorporated here somehow.  @Rockstar04 did you start this fork?

**Comment by Rockstar04** [comment] 2019-02-22 20:33
I started the fork pdf2htmlEX/pdf2htmlEX to allow continued development through contributions by other developers. The repository rockstar04/pdf2htmlEX is my aggregation of any patch I could find to build pdf2htmlEX with more modern dependencies for my own use.

**Comment by stephengaito** [comment] 2020-06-30 15:07
This issue has been fixed multiple times since the summer of 2019.

As of today, pdf2htmlEX version 0.18.8.rc1 uses Poppler version 0.89.0 (which is the latest released version of Poppler).

**Closed by stephengaito** 2020-06-30 15:07 UTC
Labels: dependencies, help wanted
